.TH "basic_data_t" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
basic_data_t
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <requetes\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBcode\fP"
.br
.ti -1c
.RI "char \fBdata\fP [\fBMAX_BUFF\fP]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure représentant une requête basique 
.SH "Member Data Documentation"
.PP 
.SS "int basic_data_t::code"
Code de la requête 
.SS "char basic_data_t::data[\fBMAX_BUFF\fP]"
Données de la requête 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
