.TH "Carte" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Carte
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <struct\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBCouleur\fP \fBCouleur\fP"
.br
.ti -1c
.RI "\fBValeur\fP \fBValeur\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBCarte\fP du jeu 
.SH "Member Data Documentation"
.PP 
.SS "\fBCouleur\fP Carte::Couleur"
\fBCouleur\fP de la carte 
.SS "\fBValeur\fP Carte::Valeur"
\fBValeur\fP ou type spécial de la carte 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
