.TH "src/common.c" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/common.c
.SH SYNOPSIS
.br
.PP
\fR#include <stdio\&.h>\fP
.br
\fR#include <string\&.h>\fP
.br
\fR#include <stdarg\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDEBUG_PRINT\fP   0"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBdebugprintf\fP (char *format,\&.\&.\&.)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void debugprintf (char * format,  \&.\&.\&.)"
Affiche un message de débogage 
.PP
\fBParameters\fP
.RS 4
\fIformat\fP Format du message 
.br
\fI\&.\&.\&.\fP Arguments du message 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
