.TH "includes/enhanceTerminal.h" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
includes/enhanceTerminal.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBclearScreen\fP()"
.br
.ti -1c
.RI "#define \fBsetTerm\fP(param)"
.br
.ti -1c
.RI "#define \fBresetTerm\fP()"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum { \fBBLACK\fP = 30, \fBRED\fP, \fBGREEN\fP, \fBYELLOW\fP, \fBBLUE\fP, \fBMAGENTA\fP, \fBCYAN\fP, \fBWHITE\fP, \fBBOLD\fP = 1, \fBFAINT\fP, \fBITALIC\fP, \fBUNDERLINE\fP, \fBBLINK\fP, \fBINV\fP = 7, \fBHIDDEN\fP, \fBSTRIKETHROUGH\fP }"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define clearScreen()"
\fBValue:\fP
.nf
{ printf("\\033[H\\033[2J");fflush(stdout); }
.PP
.fi
Efface le terminal 
.SS "#define resetTerm()"
\fBValue:\fP
.nf
setTerm(0)
.PP
.fi
Réinitialise le style de texte 
.SS "#define setTerm( param)"
\fBValue:\fP
.nf
{ printf("\\033[1m\\033[%dm", param); fflush(stdout); }
.PP
.fi
Applique un style de texte 
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
