.TH "includes/inc.h" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
includes/inc.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBPORT_SVC\fP   5010"
.br
.ti -1c
.RI "#define \fBADRESSE_SVC\fP   '127\&.0\&.0\&.1'"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ADRESSE_SVC   '127\&.0\&.0\&.1'"
Adresse du serveur 
.SS "#define PORT_SVC   5010"
Port du serveur 
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
