.TH "Joueur" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Joueur
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <struct\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBsocket_t\fP \fBidSocket\fP"
.br
.ti -1c
.RI "int \fBidJoueur\fP"
.br
.ti -1c
.RI "int \fBtailleMain\fP"
.br
.ti -1c
.RI "\fBCarte\fP * \fBmain\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBJoueur\fP 
.SH "Member Data Documentation"
.PP 
.SS "int Joueur::idJoueur"
Identifiant du joueur 
.SS "\fBsocket_t\fP Joueur::idSocket"
Socket du joueur 
.SS "\fBCarte\fP* Joueur::main"
Main du joueur 
.SS "int Joueur::tailleMain"
Taille de la main du joueur 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
