.TH "maille" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
maille
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <liste\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBT_Elt\fP \fBelt\fP"
.br
.ti -1c
.RI "struct \fBmaille\fP * \fBsuivant\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure de liste chainée 
.SH "Member Data Documentation"
.PP 
.SS "\fBT_Elt\fP maille::elt"
élément de la maille courante 
.SS "struct \fBmaille\fP* maille::suivant"
pointeur sur l'élément suivant 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
