.TH "rejoindre_partie_t" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rejoindre_partie_t
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <requetes\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBidClient\fP"
.br
.ti -1c
.RI "int \fBisPrivate\fP"
.br
.ti -1c
.RI "int \fBcode\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure contenant les informations pour rejoindre une partie 
.SH "Member Data Documentation"
.PP 
.SS "int rejoindre_partie_t::code"
Code de la partie 
.SS "int rejoindre_partie_t::idClient"
Identifiant du client 
.SS "int rejoindre_partie_t::isPrivate"
Indicateur de partie privée (1) ou publique (0) 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
